In [ ]:
from google.colab import drive
import numpy as np
import PIL
from PIL import ImageOps
import numpy as np
import pandas
from sklearn.svm import SVC as SupportVectorClassifier
from sklearn import preprocessing

In [ ]:
#some initialization
drive.mount('/content/drive')
trainData = pandas.read_csv("/content/drive/My Drive/mnist_train.csv")

#get the training data
features = trainData.drop(columns = "label") #drop the labels
labels = trainData.get("label") #label column only

#do some scaling
featuresTrain = preprocessing.scale(features)

#training
model = SupportVectorClassifier()
model.fit(featuresTrain, labels)




In [ ]:
#matrix input as np array
def getMatrixDigits(matrix):
  digits = [] #array to store each parsed digit
  matrix = np.array(matrix)
  for x in range(3):
    for y in range(3):
      image = matrix[x*28 : (x+1)*28, y*28 : (y+1)*28]
      image = preprocessing.scale(image)
      digits.append(image)
  return digits #returns array of images

#digit is a 28x28 scaled image
def predictDigit(digit):
  digit = digit.reshape(1, -1)
  prediction = model.predict(digit)
  return prediction #returns what the model predicts (int)

#extract the matrix(testing placeholder for now)
matrix = PIL.Image.open("matrix_valid_3x3_964.png")
matrix = PIL.ImageOps.invert(matrix)




#parse the matrix into individual images
digits = getMatrixDigits(matrix)
predictions = []
for digit in digits:
  predictions.append(predictDigit(digit))

#concatenate the predictions into a 3x3 matrix
matrix = np.empty((3,3))
for i in range(3):
  for j in range(3):
    matrix[i][j] = int(predictions[i*3 + j][0])

#print the matrix
print(matrix)



[[9. 6. 4.]
 [4. 7. 7.]
 [8. 4. 8.]]
